-- Eliminar todas las rúbricas existentes
DELETE FROM cnpie_rubricas;

-- 2A: Consolidados (100 pts total)
INSERT INTO cnpie_rubricas (categoria, criterio, indicador, puntaje_maximo, orden, ejemplos) VALUES
('2A', 'Intencionalidad', 'Identifica el problema, causas, consecuencias y justifica la necesidad de la innovación para la transformación educativa.', 25, 1, '[{"codigo": "1.1", "texto": "Identifica el problema, causas y consecuencias con evidencias cualitativas y cuantitativas.", "puntaje": 15}, {"codigo": "1.2", "texto": "Justifica necesidad, importancia y relevancia de la innovación para la transformación educativa.", "puntaje": 10}]'),
('2A', 'Originalidad', 'Describe propuesta innovadora con objetivos claros y estrategias diferenciadas.', 30, 2, '[{"codigo": "2.1", "texto": "Describe propuesta innovadora, sus componentes y estrategias de aplicación diferenciadas del contexto.", "puntaje": 15}, {"codigo": "2.2", "texto": "Formula objetivo general y específicos coherentes con el problema y propuesta.", "puntaje": 15}]'),
('2A', 'Impacto', 'Describe resultados, beneficios y comunica aprendizajes de la experiencia.', 20, 3, '[{"codigo": "3.1", "texto": "Describe resultados cualitativos y cuantitativos del impacto en beneficiarios.", "puntaje": 10}, {"codigo": "3.2", "texto": "Comunica aprendizajes y beneficios de la experiencia innovadora.", "puntaje": 10}]'),
('2A', 'Sostenibilidad', 'Describe estrategias de mejora continua, institucionalización y uso eficiente de recursos.', 25, 4, '[{"codigo": "4.1", "texto": "Describe estrategias de mejora continua incorporando reflexión y retroalimentación.", "puntaje": 10}, {"codigo": "4.2", "texto": "Describe acciones de institucionalización y escalabilidad.", "puntaje": 10}, {"codigo": "4.3", "texto": "Describe uso de bienes y servicios para sostenibilidad a largo plazo.", "puntaje": 5}]');

-- 2B: En Proceso (100 pts total)
INSERT INTO cnpie_rubricas (categoria, criterio, indicador, puntaje_maximo, orden, ejemplos) VALUES
('2B', 'Intencionalidad', 'Identifica el problema, causas, consecuencias y justifica la necesidad de la innovación.', 25, 1, '[{"codigo": "1.1", "texto": "Identifica el problema, causas y consecuencias con evidencias cualitativas y cuantitativas.", "puntaje": 15}, {"codigo": "1.2", "texto": "Justifica necesidad, importancia y relevancia de la innovación para la transformación educativa.", "puntaje": 10}]'),
('2B', 'Originalidad', 'Describe propuesta innovadora con objetivos claros y estrategias diferenciadas.', 30, 2, '[{"codigo": "2.1", "texto": "Describe propuesta innovadora, sus componentes y estrategias de aplicación diferenciadas.", "puntaje": 15}, {"codigo": "2.2", "texto": "Formula objetivo general y específicos coherentes con el problema y propuesta.", "puntaje": 15}]'),
('2B', 'Pertinencia', 'Sustenta pertinencia de la propuesta para atender el problema.', 10, 3, '[{"codigo": "3.1", "texto": "Sustenta pertinencia de la propuesta innovadora para atender el problema identificado.", "puntaje": 10}]'),
('2B', 'Impacto', 'Describe resultados esperados y mecanismos de medición del impacto.', 20, 4, '[{"codigo": "4.1", "texto": "Describe resultados cualitativos y cuantitativos esperados del impacto.", "puntaje": 10}, {"codigo": "4.2", "texto": "Describe mecanismos de medición y seguimiento del impacto.", "puntaje": 10}]'),
('2B', 'Sostenibilidad', 'Describe estrategias de mejora continua y uso eficiente de recursos.', 15, 5, '[{"codigo": "5.1", "texto": "Describe estrategias de mejora continua con reflexión y retroalimentación.", "puntaje": 10}, {"codigo": "5.2", "texto": "Describe uso de bienes y servicios para sostenibilidad.", "puntaje": 5}]');

-- 2C: Promisorios (100 pts total)
INSERT INTO cnpie_rubricas (categoria, criterio, indicador, puntaje_maximo, orden, ejemplos) VALUES
('2C', 'Intencionalidad', 'Identifica el problema, causas, consecuencias y justifica la necesidad de la innovación.', 25, 1, '[{"codigo": "1.1", "texto": "Identifica el problema, causas y consecuencias con evidencias cualitativas y cuantitativas.", "puntaje": 15}, {"codigo": "1.2", "texto": "Justifica necesidad, importancia y relevancia de la innovación para la transformación educativa.", "puntaje": 10}]'),
('2C', 'Originalidad', 'Describe propuesta innovadora con objetivos claros y estrategias diferenciadas.', 30, 2, '[{"codigo": "2.1", "texto": "Describe propuesta innovadora, sus componentes y estrategias de aplicación diferenciadas.", "puntaje": 15}, {"codigo": "2.2", "texto": "Formula objetivo general y específicos coherentes con el problema y propuesta.", "puntaje": 15}]'),
('2C', 'Pertinencia', 'Sustenta pertinencia de la propuesta para atender el problema.', 10, 3, '[{"codigo": "3.1", "texto": "Sustenta pertinencia de la propuesta innovadora para atender el problema identificado.", "puntaje": 10}]'),
('2C', 'Participación', 'Describe actores de la comunidad educativa y sus roles en la innovación.', 10, 4, '[{"codigo": "4.1", "texto": "Describe actores de la comunidad educativa involucrados y sus roles.", "puntaje": 10}]'),
('2C', 'Reflexión', 'Sustenta estrategias para promover participación activa y reflexión de actores.', 10, 5, '[{"codigo": "5.1", "texto": "Sustenta estrategias para promover participación activa y reflexión de actores educativos.", "puntaje": 10}]'),
('2C', 'Sostenibilidad', 'Describe estrategias de mejora continua y uso eficiente de recursos.', 15, 6, '[{"codigo": "6.1", "texto": "Describe estrategias de mejora continua con reflexión y retroalimentación.", "puntaje": 10}, {"codigo": "6.2", "texto": "Describe uso de bienes y servicios para sostenibilidad.", "puntaje": 5}]');

-- 2D: IAPE (100 pts total)
INSERT INTO cnpie_rubricas (categoria, criterio, indicador, puntaje_maximo, orden, ejemplos) VALUES
('2D', 'Intencionalidad', 'Identifica problema de investigación, formula preguntas y objetivos vinculados.', 45, 1, '[{"codigo": "1.1", "texto": "Identifica el problema de investigación, causas y consecuencias con evidencias cualitativas y cuantitativas.", "puntaje": 15}, {"codigo": "1.2", "texto": "Justifica la necesidad, importancia y relevancia de la investigación para la transformación educativa.", "puntaje": 10}, {"codigo": "1.3", "texto": "Formula preguntas de investigación principal y específicas vinculadas al problema.", "puntaje": 10}, {"codigo": "1.4", "texto": "Formula objetivo general y específicos en relación con el problema y preguntas.", "puntaje": 10}]'),
('2D', 'Participación', 'Identifica actores del equipo de investigación y describe sus roles en el marco IAPE.', 10, 2, '[{"codigo": "2.1", "texto": "Identifica actores del equipo de investigación y describe roles en el marco IAPE.", "puntaje": 10}]'),
('2D', 'Reflexión', 'Sustenta estrategias para promover participación activa y reflexión dialógica en marco IAPE.', 10, 3, '[{"codigo": "3.1", "texto": "Sustenta estrategias para promover participación activa y reflexión dialógica en marco IAPE.", "puntaje": 10}]'),
('2D', 'Consistencia', 'Describe procedimiento metodológico, técnicas e instrumentos, plan de actividades y uso de recursos.', 35, 4, '[{"codigo": "4.1", "texto": "Describe procedimiento metodológico cíclico para alcanzar objetivos en marco IAPE.", "puntaje": 10}, {"codigo": "4.2", "texto": "Describe técnicas e instrumentos de recolección y análisis de datos vinculados a objetivos.", "puntaje": 10}, {"codigo": "4.3", "texto": "Presenta plan de actividades y responsabilidades vinculado a objetivos.", "puntaje": 10}, {"codigo": "4.4", "texto": "Describe utilidad de bienes y servicios para sostenibilidad a largo plazo.", "puntaje": 5}]');