// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihgfqdmcndcyzzsbliyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImloZ2ZxZG1jbmRjeXp6c2JsaXlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2MDYzOTksImV4cCI6MjA2ODE4MjM5OX0.3vxIlKGaiHsfQ7ApnNCLNUNRkx6riC3FANSsrJrXXWg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});